// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "EnumEntry.idl";

namespace Microsoft.Terminal.Settings.Editor
{
    runtimeclass RebindKeysEventArgs
    {
        Microsoft.Terminal.Control.KeyChord OldKeys { get; };
        Microsoft.Terminal.Control.KeyChord NewKeys { get; };
    }

    runtimeclass ActionAndArgsViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        String Name { get; };
        Microsoft.Terminal.Settings.Model.ActionAndArgs ActionData { get; };
    }

    runtimeclass KeyBindingViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        // Settings Model side
        String Name { get; };
        String KeyChordText { get; };

        // UI side
        Boolean IsInEditMode { get; };
        String ProposedKeys;
        Windows.UI.Xaml.Controls.Flyout AcceptChangesFlyout;
        IObservableVector<ActionAndArgsViewModel> AvailableActions { get; };
        ActionAndArgsViewModel CurrentAction;
        void ToggleEditMode();
        void AttemptAcceptChanges();
        void DeleteKeyBinding();

        event Windows.Foundation.TypedEventHandler<KeyBindingViewModel, RebindKeysEventArgs> RebindKeysRequested;
        event Windows.Foundation.TypedEventHandler<KeyBindingViewModel, Microsoft.Terminal.Control.KeyChord> DeleteKeyBindingRequested;
    }

    runtimeclass ActionsPageNavigationState
    {
        Microsoft.Terminal.Settings.Model.CascadiaSettings Settings;
    };

    [default_interface] runtimeclass Actions : Windows.UI.Xaml.Controls.Page
    {
        Actions();
        ActionsPageNavigationState State { get; };

        IObservableVector<KeyBindingViewModel> KeyBindingList { get; };
    }
}
